project:
  type: website
  output-dir: docs

website:
  title: "Katherine Cox"
  navbar:
    right:
      - about.qmd
      - text: On My Mind
        href: on-my-mind/
      - icon: github
        href: https://github.com/KatherineCox

format:
  html:
    theme: yeti
    css: styles.css



